supreme2580/stark-squeeze

- .gitignore
- dist/imageToBase64.d.ts
- dist/imageToBase64.js
- package.json
- pnpm-lock.yaml
- src/index.ts
Closes: https://github.com/supreme2580/stark-squeeze/issues/6
> implement pinata upload functionality

- src/index.ts
Closes: https://github.com/supreme2580/stark-squeeze/issues/8
> get file back

- contracts/src/lib.cairo
Closes: https://github.com/supreme2580/stark-squeeze/issues/24
> add more fields

- contracts/src/lib.cairo
Closes: https://github.com/supreme2580/stark-squeeze/issues/18
> Get data back from address

- contracts/Scarb.toml
- contracts/src/lib.cairo
> fix: fix scarb and cid

- contracts/src/lib.cairo
> Implement file format in contract

- src/decompression/decompressWithBrotli.ts
- src/decompression/index.ts
Closes #54 
- **Input**: Accepts a compressed Buffer data.
- **Processing**: Utilizes `brotliDecompressSync` from Node.js's zlib module to perform synchronous decompression.
- **Output**: Returns the decompressed data as a UTF-8 encoded string.
> Implement `decompressWithBrotli` Function

- contracts/src/lib.cairo
> encryption

- package.json
- pnpm-lock.yaml
- src/compression/binaryToDots.ts
> BinaryToDots

- contracts/src/lib.cairo
implement `field_type`  field to the following 
1- set function 
2- get function
3- storage
4- struct 
Close: #52
> feat: implement field_type

- package.json
- test/decompression/binarytodots.test.ts
> test: implement test for binarytodots function

- src/compression/binaryToDots.ts
> documentation

- src/decompression/dotsToBinary.ts
> docs: implement proper doc for dotstobinary function

- src/reconstruction/binaryToBuffer.ts
Closes: #62 
Implemented `binaryToBuffer` following the next algorithm:
- Evaluate the validity of the binaryStr param to check it is a valid input (only 0s and 1s as allowed chars).
- Split the string into chunks of 8-bit and store them into a chuncks array (before I will pad with zeros if it's necesary).
- Convert each item of the chunks array into a byte and store each of them on a bytes array.
- Finally create and return a buffer using the function Buffer.from, passing as param the bytes array.
I'm attentive to any correction🚀
> [issue #62] implement binaryToBuffer function

- src/decompression/index.ts
- src/decompression/reverseSecondDict.ts
> feat:reverseSecondDict function

- src/compression/applySecondDict.test.ts
- src/compression/applySecondDict.ts
- src/compression/index.ts
**Overview of Changes:**
1. **Implementation:**  
- We created the `applySecondDict` function in `compression/applySecondDict.ts` to process an encoded string by sequentially scanning for the longest matching dot pattern from our dictionary.  
- The function ensures that overlapping patterns are correctly handled by sorting the dictionary keys in descending order of length and matching the longest pattern at each step.
2. **Dictionary Storage:**  
- The dot-to-symbol mappings are stored in `constants/dictionaries.ts` to keep configuration data separate from business logic, promoting modularity and ease of maintenance.
3. **Testing:**  
- A dedicated test file (`compression/applySecondDict.test.ts`) verifies the correctness of our function, ensuring it handles various scenarios including …
> Implement applySecondDict Function #43

- src/reconstruction/binaryToBuffer.ts
Added documentation for binaryToBuffer function
Resolves #63
> feat: docs for binaryToBuffer function

- test/reconstruction/binarytobuffer.test.ts
> test: add test for binarytobuffer function

- src/decompression/decompressWithBrotli.ts
> feat: docs for decompresswithBrotli

- contracts/src/lib.cairo
> added name to contract

- src/compression/compressWithBrotli.ts
fix issue #47 
Implemented proper documentation for compressWithBrotli
> documentation: fix issue 47

- rust-v2/src/main.rs
> file to binary

- rust-v2/constants.rs
> splitBy5Function

- README.md
> Update README with Dictionary File Size

- indexer/.env.example
- indexer/.gitignore
- indexer/apibara.config.ts
- indexer/bun.lock
- indexer/drizzle.config.ts
- indexer/indexers/file-uploads.indexer.ts
- indexer/lib/constants.ts
- indexer/lib/contract-abi.ts
- indexer/lib/event-handlers.ts
- indexer/lib/schema.ts
- indexer/package-lock.json
- indexer/package.json
- indexer/tsconfig.json
- Add comprehensive database schema for all contract events
- Implement event handlers using Apibara's decodeEvent for automatic type conversion
- Create modular architecture with proper TypeScript typings
- Support all contract events: CompressionMappingStored, FileUploaded, FileUpdated, FileDeleted, FileShared
- Handle multi-part integers (u256) and complex data types automatically
- Add contract ABI definitions for proper event decoding
- Ensure data is structured for easy API access
- Closes #254
> feat: implement robust Apibara indexer with decodeEvent

- contracts/.tool-versions
- contracts/src/tests.cairo
This PR adds a complete test suite for the **Starksqueeze** smart contract to address [#249](https://github.com/your-repo/issues/249) (**Missing Smart Contract Tests**).  
The goal is to ensure high confidence in contract functionality, improve maintainability, and validate both normal and edge case behaviors.
- Added **unit tests** for all core contract functions:
- `constructor`
- `upload_file`
- `get_user_files`
- `delete_file`
- `access_control`
- Implemented **error case tests**:
- Duplicate file uploads
- Unauthorized access
- Added **integration-style tests** covering user workflows.
- Verified **event emissions**.
- Ensured **access control enforcement** for admin-only functions.
- Configured **test dependencies** in `Scarb.toml`.
- Enabled **coverage reports** (`scarb test …
> Add enhance tests for file upload, visibility, sharing, and access control
